spring:
  application:
    name: smartsplit

  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    listener:
      simple:
        retry:
          enabled: true
          initial-interval: 3s
          max-attempts: 5

  datasource:
    url: jdbc:postgresql://localhost:5432/smartsplit
    username: postgres
    password: Anjali123
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true

application:
  security:
    jwt:
      secret-key: "MySuperSecureSecretKeyForJwt12345678901234567890"
      expiration: 86400000

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    enabled: true
    operations-sorter: method
    tags-sorter: alpha
  api-docs:
    path: /v3/api-docs
  show-actuator: false
